### ISSUE TITLE
Indentation does not appear to work

### ISSUE THREAD

**Issue by kritixilithos** [leanprover/lean-mode#20]
`TAB` in the beginning of the line gives an error

    Symbol’s function definition is void: position-if

instead of indenting. Looks like it refers to this line https://github.com/leanprover/lean-mode/blob/b5ba739f68ef731c03247bf6db2708502c8ac46c/lean-eri.el#L31

(lean-mode installed from melpa)

**Comment by Kha** [comment]
Emacs version?

**Comment by kritixilithos** [comment]
Emacs 26.3

**Comment by Kha** [comment]
I see, this was broken in https://github.com/leanprover/lean-mode/pull/18. I don't use Lean 3 anymore, so I didn't notice. If you figure out a solution using `cl-lib`, a PR would be greatly appreciated!

**Comment by kritixilithos** [comment]
I made a pull request that fixes `TAB`, but block indentation (via `C-M-\`) indents all the lines to the same column. Is this intended?

**Comment by Kha** [comment]
I don't know, I don't think I've ever tried that.
