### ISSUE TITLE
Porting to emacs 28's newer eldoc versions

### ISSUE THREAD

**Issue by kritixilithos** [leanprover/lean-mode#33]
Some cool changes have been added to the latest versions of eldoc (available in emacs 28), such as no longer having to manually handle `eldoc-echo-area-use-multiline-p` (and other settings) in `eldoc-documentation-function`. It would be worth porting to it for emacs 28 users, whilst retaining existing behaviour for those on emacs versions < 28.0. Particularly, instead of the package truncating the docs with an ellipsis (as seen for docs of tactics like `simp`), for emacs 28 users the full docs can be returned, leaving it to the user to, for example, choose their echo area size.

I have started working on this, if you think this is a good idea, I'll polish my changes and create a pull request.

**Comment by Kha** [comment]
For Lean 4 this will hopefully be taken care of by lsp-mode, but I don't mind merging any improvements for Lean 3!
