### ISSUE TITLE
lean server sync: (json-readtable-error 99)

### ISSUE THREAD

**Issue by Alf0nso** [leanprover/lean-mode#36]
Hey hey, I might be doing something wrong..
Once I open a lean file I get the error on the title

Emacs version:
GNU Emacs 27.1 (build 1, x86_64-w64-mingw32) of 2020-08-21

lean version:
Lean (version 4.0.0-m2, commit 26dda3f63d88, Release)

(maybe I should be using an older version of lean?
sorry, I'm really new to the language)

**Comment by Kha** [comment]
This extension is for Lean 3. For Lean 4, please follow the instructions at https://leanprover.github.io/lean4/doc/setup.html.
