### ISSUE TITLE
(json-unknown-keyword fish)

### ISSUE THREAD

**Issue by fusiongyro** [leanprover/lean-mode#4]
I get an error ending in this message `(json-unknown-keyword fish)` on most any event: opening a file, scrolling the window, etc. So I have not gotten very far in my Lean adventure. :)

I suspect this has something to do with my shell being fish, but I am having some trouble debugging the issue further. Changing my shell to bash has changed the error to `(json-readtable-error)`. Is there a configuration step I'm missing?

**Comment by Kha** [comment]
What emacs version are you using? Can you see the full error message after
`M-x lean-turn-on-debug-mode`?

**Comment by fusiongyro** [comment]
The problem turned out to be that I had assigned the path incorrectly. Sorry to waste your time!

**Comment by Kha** [comment]
No problem. I pushed a commit that raises an explicit error if `lean-rootdir` is not correct.
