### ISSUE TITLE
Naming of lean-mode and lean4-mode

### ISSUE THREAD

**Issue by mekeor** [leanprover/lean-mode#48]
lean-mode for Lean version 3 is maintained as part of the leanprover Github organization and available via Melpa. lean4-mode for Lean version 4 is maintained in a separate repository under the leanprover-community organization and is not yet available via Melpa. For users, who are unfamiliar with this situation, this may be confusing.

1. What do you think about renaming *lean-mode* to *lean3-mode*?

2. What do you think about moving the lean4-mode repository to the repository where lean-mode currently resides? The current lean-mode could then move to leanprover/lean3-mode, for example.

3. How complicated would it be to merge both repositories so that we have one package which supports both versions of Lean?

<hr>

Related:
- lean4-mode repository, issue "Rename to 'Lean mode' / 'lean-mode'": https://github.com/leanprover-community/lean4-mode/issues/70
- Melpa repository, PR "Add recipe for Nael" (a fork of lean4-mode), comment related to naming: https://github.com/melpa/melpa/pull/9098#issuecomment-2227407367

**Comment by Kha** [comment]
Thanks, I will rename and archive this repo as it is, and should be, truly dead. It should probably be removed from Melpa.

> What do you think about moving the lean4-mode repository to the repository where lean-mode currently resides

lean4-mode is a community project. The lean4 prefix is consistent with other repos, such as lean4 itself.

> How complicated would it be to merge both repositories so that we have one package which supports both versions of Lean?

Given that no-one should use lean3-mode, I don't see a need for that
